package MVC.Model;

public enum TokenType {
  RW_BEGIN, RW_END, RW_READ, RW_PRINT, RW_IF,
  RW_ELSE, RW_WHILE, RW_CONTINUE, RW_BREAK,
  RW_EXIT, RW_INT, RW_STRING, IDENTIFIER, INTEGER,
  STRING, LEFT_PARENTHESES, RIGHT_PARENTHESES,
  LEFT_CURLY_BRACE, RIGHT_CURLY_BRACE, ASSIGNMENT,
  EQUALS, NOT_EQUALS, LESS, LESS_EQUALS, GREATER,
  GREATER_EQUALS, ADD, SUBSTRACT;
}